services:
  deckster-db:
    container_name: deckster-db
    build:
      context: ./Domain/Database
    env_file:
      - api.env
    networks:
      - deckster_net
    volumes:
      - ${DB_DATA}:/var/opt/mssql

  deckster-blazor:
    container_name: deckster-blazor
    build:
      context: ./
      dockerfile: ./Blazor.Dockerfile
    env_file:
      - blazor.env
    networks:
      - deckster_net
      - caddy_net    
    volumes:
      - ${SHARED_KEYS}:/data

  deckster-api:
    container_name: deckster-api
    build:
      context: ./
      dockerfile: ./API.Dockerfile
    env_file:
      - api.env
    networks:
      - deckster_net
      - caddy_net

networks:
  deckster_net:
    external: true 
  caddy_net:
    external: true
